FROM ghcr.io/endorhq/rover/node:v1.3.4

# Use an older version of the alpine package index to get ruby 3.2
RUN apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/v3.19/main ruby=3.2.8-r0 ruby-dev=3.2.8-r0 build-base=0.5-r3
