FROM ghcr.io/endorhq/rover/node:v1.3.4

# Use an older version of the alpine package index to get ruby 3.1
RUN apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/v3.17/main ruby ruby-dev build-base
